//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WithOutSmoke.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WithOutSmoke.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\&apos;cf\&apos;e5\&apos;f0\&apos;e2\&apos;fb\&apos;e9\f1\lang1033  \f0\lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\b0\f1\lang1033\par
        ///
        ///\pard 
        ///{\pntext\f1 1.\tab}{\*\pn\pnlvlbody\pnf1\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li360\sl276\slmult1\f0\lang1049\&apos;d1\&apos;ed\&apos;e8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c4\&apos;e5\&apos;f1\&apos;ff\&apos;f2\&apos;fb\&apos;e9 \lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\b0\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;d2\&apos;e5 \&apos;ef\&apos;f0\&apos;ee\&apos;f6\&apos;e5\&apos;f1\&apos;f1\&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c4\&apos;e5\&apos;f1\&apos;ff\&apos;f2\&apos;fb\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///
        ///\pard\widctlpar\sl276\slmult1\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;cc\&apos;ed\&apos;ee\&apos;e3\&apos;e8\&apos;e5 \&apos;e7\&apos;e0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10m {
            get {
                return ResourceManager.GetString("_10m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;ce\&apos;e4\&apos;e8\&apos;ed\&apos;ed\&apos;e0\&apos;e4\&apos;f6\&apos;e0\&apos;f2\&apos;fb\&apos;e9 \lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\b0\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;ce\&apos;e4\&apos;e8\&apos;ed\&apos;ed\&apos;e0\&apos;e4\&apos;f6\&apos;e0\&apos;f2\&apos;fb\&apos;e9\f1\lang1033  \f0\lang1058\&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\f1\lang1033\par
        ///\par
        ///
        ///\pard 
        ///{\pntext\f1 1.\tab}{\*\pn\pnlvlbody\pnf1\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11m {
            get {
                return ResourceManager.GetString("_11m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c4\&apos;e2\&apos;e5\&apos;ed\&apos;e0\&apos;e4\&apos;f6\&apos;e0\&apos;f2\&apos;fb\&apos;e9 \lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;cd\&apos;ee\&apos;f0\&apos;ec\&apos;e0\&apos;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c4\&apos;e2\&apos;e5\&apos;ed\&apos;e0\&apos;e4\&apos;f6\&apos;e0\&apos;f2\&apos;fb\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\b0\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;d2\&apos;e5\&apos;ef\&apos;e5\&apos;f0\&apos;fc \&apos;f0\&apos;e8\&apos;f1\&apos;ea \&apos;f0\&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12m {
            get {
                return ResourceManager.GetString("_12m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d2\&apos;f0\&apos;e8\&apos;ed\&apos;e0\&apos;e4\&apos;f6\&apos;e0\&apos;f2\&apos;fb\&apos;e9 \lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;c8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d7\&apos;e5\&apos;f2\&apos;fb\&apos;f0\&apos;ed\&apos;e0\&apos;e4\&apos;f6\&apos;e0\&apos;f2\&apos;fb\&apos;e9 \lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;c7\&apos;e0\&apos;e6\&apos;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;cf\&apos;e5\&apos;f0\&apos;e2\&apos;fb\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;c7\&apos;e0\&apos;eb\&apos;ee\&apos;e6\&apos;e5\&apos;ed\&apos;fb \&apos;ee\&apos;f1\&apos;ed\&apos;ee\&apos;e2\&apos;fb \&apos;e4\&apos;eb\&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1m {
            get {
                return ResourceManager.GetString("_1m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c2\&apos;f2\&apos;ee\&apos;f0\&apos;ee\&apos;e9\f1\lang1033  \f0\lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\b0\f1\lang1033\par
        ///
        ///\pard 
        ///{\pntext\f1 1.\tab}{\*\pn\pnlvlbody\pnf1\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\f0\lang1049\&apos;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c2\&apos;f2\&apos;ee\&apos;f0\&apos;ee\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\b0\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;ca\&apos;eb\&apos;e5\&apos;f2\&apos;ea\&apos;e8 \&apos;ea\&apos;ee\&apos;e6\&apos;e8 \&apos;ef\&apos;f0\&apos;ee\&apos;f8\&apos;eb\&apos;e8 \ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2m {
            get {
                return ResourceManager.GetString("_2m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d2\&apos;f0\&apos;e5\&apos;f2\&apos;e8\&apos;e9\f1\lang1033  \f0\lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\b0\f1\lang1033\par
        ///
        ///\pard 
        ///{\pntext\f1 1.\tab}{\*\pn\pnlvlbody\pnf1\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\f0\lang1049\&apos;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d2\&apos;f0\&apos;e5\&apos;f2\&apos;e8\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\b0\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;cd\&apos;e0\&apos;f7\&apos;e8\&apos;ed\&apos;e0\&apos;e5\&apos;f2\&apos;f1\&apos;ff \&apos;ef\&apos;ee\&apos;eb\&apos;ed\&apos;ee\&apos;f6\&apos;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3m {
            get {
                return ResourceManager.GetString("_3m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d7\&apos;e5\&apos;f2\&apos;e2\&apos;e5\&apos;f0\&apos;f2\&apos;fb\&apos;e9\lang1049  \&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\b0\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;cf\&apos;f0\&apos;e8\&apos;f2\&apos;ee\&apos;ea \&apos;ea\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d7\&apos;e5\&apos;f2\&apos;e2\&apos;e5\&apos;f0\&apos;f2\&apos;fb\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;ca\&apos;eb\&apos;e5\&apos;f2\&apos;ea\&apos;e8 \&apos;ea\&apos;ee\&apos;e6\&apos;e8 \&apos;ee\&apos;e1\&apos;ed\&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4m {
            get {
                return ResourceManager.GetString("_4m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;cf\&apos;ff\&apos;f2\&apos;fb\&apos;e9\lang1049  \&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;c7\&apos;e0\&apos;e6\&apos;e8\&apos;e2\&apos;e0\&apos;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;cf\&apos;ff\&apos;f2\&apos;fb\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\b0\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;d2\&apos;f0\&apos;f3\&apos;e4\&apos;ed\&apos;e5\&apos;e5 \&apos;e2\&apos;f1\&apos;e5\&apos;e3\&apos;ee \&apos;ef\&apos;f0\&apos;e8\&apos;f5\&apos;ee\&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5m {
            get {
                return ResourceManager.GetString("_5m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049 5 \&apos;f8\&apos;ee\&apos;ea\&apos;e8\&apos;f0\&apos;f3\&apos;fe\&apos;f9\&apos;e8\&apos;f5 \&apos;e2\&apos;e5\&apos;f9\&apos;e5\&apos;f1\&apos;f2\&apos;e2 \&apos;e2 \&apos;f1\&apos;ee\&apos;f1\&apos;f2\&apos;e0\&apos;e2\&apos;e5 \&apos;f1\&apos;e8\&apos;e3\&apos;e0\&apos;f0\&apos;e5\&apos;f2\&apos;fb\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\b0\tab\&apos;ca\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5 \&apos;e2\&apos;f0\&apos;e5\&apos;e4\&apos;e8\&apos;f2 \&apos;ed\&apos;e0\&apos;f8\&apos;e5\&apos;ec\&apos;f3 \&apos;ee\&apos;f0\&apos;e3\&apos;e0\&apos;ed\&apos;e8\&apos;e7\&apos;ec\&apos;f3. \&apos;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5things {
            get {
                return ResourceManager.GetString("_5things", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d8\&apos;e5\&apos;f1\&apos;f2\&apos;ee\&apos;e9\lang1049  \&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;d3\&apos;f1\&apos;e8\&apos;eb\&apos;e8\&apos;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d8\&apos;e5\&apos;f1\&apos;f2\&apos;ee\&apos;e9\f1\lang1033  \f0\lang1058\&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\f1\lang1033\par
        ///\b0\par
        ///
        ///\pard 
        ///{\pntext\f1 1.\tab}{\*\pn\pnlvlbody\pnf1\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\f0\lang104 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6m {
            get {
                return ResourceManager.GetString("_6m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d1\&apos;e5\&apos;e4\&apos;fc\&apos;ec\&apos;ee\&apos;e9\lang1049  \&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;dd\&apos;f2\&apos;e0\&apos;ef \&apos;f4\&apos;e8\&apos;e7\&apos;e8\&apos;f7\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;d1\&apos;e5\&apos;e4\&apos;fc\&apos;ec\&apos;ee\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\b0\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;c8\&apos;ed\&apos;f2\&apos;e5\&apos;f0\&apos;e5\&apos;f1\&apos;ed\&apos;ee, \&apos;f7\&apos;f2\&apos;ee \&apos;ec\&apos;ed\&apos;ee\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _7m {
            get {
                return ResourceManager.GetString("_7m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c2\&apos;ee\&apos;f1\&apos;fc\&apos;ec\&apos;ee\&apos;e9 \lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\b0\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;c0\&apos;ea\&apos;f2\&apos;e8\&apos;e2\&apos;e8\&apos;e7\&apos;e8\&apos;f0\&apos;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c2\&apos;ee\&apos;f1\&apos;fc\&apos;ec\&apos;ee\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;c2\&apos;fb\&apos;e4\&apos;e5\&apos;eb\&apos;e5\&apos;ed\&apos;e8\&apos;ff \&apos;f1\&apos;eb\&apos;e8\&apos;e7\&apos;e8 \&apos;ef\&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8m {
            get {
                return ResourceManager.GetString("_8m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c4\&apos;e5\&apos;e2\&apos;ff\&apos;f2\&apos;fb\&apos;e9 \lang1049\&apos;e4\&apos;e5\&apos;ed\&apos;fc\par
        ///\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\b0\&apos;d1\&apos;ee\&apos;f1\&apos;f2\&apos;ee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\widctlpar\sl276\slmult1\qc\b\f0\fs22\lang1058\&apos;c4\&apos;e5\&apos;e2\&apos;ff\&apos;f2\&apos;fb\&apos;e9 \&apos;ec\&apos;e5\&apos;f1\&apos;ff\&apos;f6\par
        ///\b0\lang1049\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-358\li409\sl276\slmult1\&apos;d1\&apos;f7\&apos;e8\&apos;f2\&apos;e0\&apos;e5\&apos;f2\&apos;f1\&apos;ff \&apos;ed\&apos;e0\&apos;f7\&apos;e0\&apos;eb\&apos;ee\&apos;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9m {
            get {
                return ResourceManager.GetString("_9m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\&apos;d1\&apos;ee\&apos;e2\&apos;e5\&apos;f2\&apos;fb \&apos;ef\&apos;ee \&apos;ee\&apos;f2\&apos;ea\&apos;e0\&apos;e7\&apos;f3 \&apos;ee\&apos;f2 \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;ff\b0\f1\lang9\par
        ///
        ///\pard 
        ///{\pntext\f1 1.\tab}{\*\pn\pnlvlbody\pnf1\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li360\sa200\sl276\slmult1\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string advice {
            get {
                return ResourceManager.GetString("advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\&apos;cf\&apos;ee\&apos;eb\&apos;fc\&apos;e7\&apos;e0 \&apos;ee\&apos;f2\&apos;ea\&apos;e0\&apos;e7\&apos;e0 \&apos;ee\&apos;f2 \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;ff\b0\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li360\sa200\sl276\slmult1\qj\&apos;d1\&apos;ed\&apos;e8\&apos;e6\&apos;e0\&apos;e5\&apos;f2\&apos;f1\&apos;ff \&apos;f0\&apos;e8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string benefit {
            get {
                return ResourceManager.GetString("benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}{\f2\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.14385}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\sl276\slmult1\qc\b\f0\fs22\&apos;d1\&apos;ee\&apos;f1\&apos;f2\&apos;e0\&apos;e2 \&apos;f2\&apos;e0\&apos;e1\&apos;e0\&apos;f7\&apos;ed\&apos;ee\&apos;e3\&apos;ee \&apos;e4\&apos;fb\&apos;ec\&apos;e0\par
        ///\par
        ///
        ///\pard{\pntext\f2\&apos;B7\tab}{\*\pn\pnlvlblt\pnf2\pnindent0{\pntxtb\&apos;B7}}\fi-360\li360\sl276\slmult1\qj\&apos;c0\&apos;ed\&apos;f2\&apos;f0\&apos;e0\&apos;f6\&apos;e5\&apos;ed  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string composition {
            get {
                return ResourceManager.GetString("composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Debug_Bug3_icon {
            get {
                object obj = ResourceManager.GetObject("Debug_Bug3_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\sl276\slmult1\qc\b\f0\fs22\&apos;c1\&apos;ee\&apos;eb\&apos;e5\&apos;e7\&apos;ed\&apos;e8 \&apos;ee\&apos;f2 \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;ff\par
        ///\par
        ///
        ///\pard\sl276\slmult1\qj\&apos;c7\&apos;eb\&apos;ee\&apos;ea\&apos;e0\&apos;f7\&apos;e5\&apos;f1\&apos;f2\&apos;e2\&apos;e5\&apos;ed\&apos;ed\&apos;fb\&apos;e5 \&apos;ee\&apos;ef\&apos;f3\&apos;f5\&apos;ee\&apos;eb\&apos;e8\par
        ///
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string desease {
            get {
                return ResourceManager.GetString("desease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\&apos;d4\&apos;e0\&apos;ea\&apos;f2\&apos;fb \&apos;ee \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e8\b0\f1\lang9\par
        ///
        ///\pard 
        ///{\pntext\f0 1.\tab}{\*\pn\pnlvlbody\pnf0\pnindent0\pnstart1\pndec{\pntxta.}}
        ///\fi-360\li360\sa200\sl276\slmult1\f0\lang1049\&apos;d2\&apos;e0\&apos;e1\&apos;e0\&apos;ea - \&apos;ea\&apos;ee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string facts {
            get {
                return ResourceManager.GetString("facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat\deflang1049\deflangfe1049\deftab708{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red255\green0\blue0;}
        ///{\*\generator Riched20 10.0.10586}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\sl276\slmult1\qc\b\f0\fs22\&apos;c8\&apos;f1\&apos;f2\&apos;ee\&apos;f0\&apos;e8\&apos;ff \&apos;f2\&apos;e0\&apos;e1\&apos;e0\&apos;ea\&apos;e0\par
        ///\b0\par
        ///
        ///\pard\sl276\slmult1\qj\b\tab\&apos;d2\&apos;e0\&apos;e1\&apos;e0\&apos;ea\&apos;ee\&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5\b0  \f1\emdash  \f0\&apos;e2\&apos;e4\&apos;fb\&apos;f5\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;ca\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5 \&apos;ea\&apos;e0\&apos;eb\&apos;fc\&apos;ff\&apos;ed\&apos;e0\b0\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\tab\&apos;ce\&apos;f2\&apos;e4\&apos;fb\&apos;f5\&apos;e0\&apos;ff \&apos;e2 \&apos;fd\&apos;ea\&apos;e7\&apos;ee\&apos;f2\&apos;e8\&apos;f7\&apos;e5\&apos;f1\&apos;ea\&apos;e8\&apos;f5 \&apos;f1\&apos;f2\&apos;f0\&apos;e0\&apos;ed\&apos;e0\&apos;f5 \&apos;c0\&apos;e7\&apos;e8\&apos;e8, \&apos;ed\&apos;e0\&apos;f8\&apos;e8 \&apos;f1\&apos;ee\&apos;ee\&apos;f2\&apos;e5\&apos;f7\&apos;e5\&apos;f1\&apos;f2\&apos;e2\&apos;e5\&apos;ed\&apos;ed\&apos;e8\&apos;ea\&apos;e8  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hookah {
            get {
                return ResourceManager.GetString("hookah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;ca\&apos;e0\&apos;ea\&apos;e8\&apos;e5 \&apos;f1\&apos;e8\&apos;e3\&apos;e0\&apos;f0\&apos;e5\&apos;f2\&apos;fb \&apos;e2\&apos;f0\&apos;e5\&apos;e4\&apos;ed\&apos;e5\&apos;e5?\b0\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\tab\&apos;d3\&apos;e6 \&apos;e8 \&apos;ed\&apos;e5 \&apos;ef\&apos;ee\&apos;ed\&apos;ff\&apos;f2\&apos;ed\&apos;ee, \&apos;f7\&apos;f2\&apos;ee \&apos;e2\&apos;fb \&apos;ee\&apos;e6\&apos;e8\&apos;e4\&apos;e0\&apos;e5\&apos;f2\&apos;e5 \&apos;f3\&apos;f1\&apos;eb\&apos;fb\&apos;f8\&apos;e0\&apos;f2\&apos;fc \&apos;e2 \&apos;ee\&apos;f2\&apos;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lightorhard {
            get {
                return ResourceManager.GetString("lightorhard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;c2\&apos;f0\&apos;e5\&apos;e4 \&apos;ed\&apos;e8\&apos;ea\&apos;ee\&apos;f2\&apos;e8\&apos;ed\&apos;e0\b0\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\tab\&apos;ce \&apos;f2\&apos;ee\&apos;ec, \&apos;f7\&apos;f2\&apos;ee \&apos;ed\&apos;e8\&apos;ea\&apos;ee\&apos;f2\&apos;e8\&apos;ed \&apos;ed\&apos;e5\&apos;e3\&apos;e0\&apos;f2\&apos;e8\&apos;e2\&apos;ed\&apos;ee \&apos;e2\&apos;ee\&apos;e7\&apos;e4\&apos;e5\&apos;e9\&apos;f1\&apos;f2\&apos;e2\&apos;f3\&apos;e5\&apos;f2 \&apos;ed\&apos;e0 \&apos;ec\&apos;ed\&apos;ee\&apos;e3\&apos;e8\&apos;e5 \&apos;f1\&apos;e8\&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nicotine {
            get {
                return ResourceManager.GetString("nicotine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;cf\&apos;e0\&apos;f1\&apos;f1\&apos;e8\&apos;e2\&apos;ed\&apos;ee\&apos;e5 \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5\b0\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\tab\&apos;d2\&apos;e0\&apos;e1\&apos;e0\&apos;ea\&apos;ee\&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5 \&apos;f1\&apos;f2\&apos;ee\&apos;e8\&apos;f2 \&apos;f1\&apos;e5\&apos;e3\&apos;ee\&apos;e4\&apos;ed\&apos;ff \&apos;ed\&apos;e0 \&apos;e2\&apos;f2\&apos;ee\&apos;f0\&apos;ee\&apos;ec \&apos;ec\&apos;e5\&apos;f1\&apos;f2\&apos;e5 \&apos;f1\&apos;f0\&apos;e5\&apos;e4\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string passive {
            get {
                return ResourceManager.GetString("passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;d1\&apos;ec\&apos;e5\&apos;f0\&apos;f2\&apos;fc \&apos;ee\&apos;f2 \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;ff\b0\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\tab\&apos;c8\&apos;e7\&apos;e2\&apos;e5\&apos;f1\&apos;f2\&apos;ed\&apos;ee\&apos;e5 \&apos;e2\&apos;fb\&apos;f1\&apos;ea\&apos;e0\&apos;e7\&apos;fb\&apos;e2\&apos;e0\&apos;ed\&apos;e8\&apos;e5 \&apos;ee \&apos;f2\&apos;ee\&apos;ec, \&apos;f7\&apos;f2\&apos;ee \&apos;ea\&apos;e0\&apos;ef\&apos;eb\&apos;ff \&apos;ed\&apos;e8\&apos;ea\&apos;ee\&apos;f2\&apos;e8\&apos;ed\&apos;e0 \&apos;f3\&apos;e1\&apos;e8\&apos;e2\&apos;e0\&apos;e5\&apos;f2 \&apos;eb\&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string smokendeath {
            get {
                return ResourceManager.GetString("smokendeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;d1\&apos;f2\&apos;e0\&apos;f2\&apos;e8\&apos;f1\&apos;f2\&apos;e8\&apos;ea\&apos;e0 \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;ff \&apos;e2 \&apos;ec\&apos;e8\&apos;f0\&apos;e5\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\b0\tab\&apos;cf\&apos;ee \&apos;e4\&apos;e0\&apos;ed\&apos;ed\&apos;fb\&apos;ec \&apos;c2\&apos;ce\&apos;c7, \&apos;ed\&apos;e0 \&apos;f1\&apos;e5\&apos;e3\&apos;ee\&apos;e4\&apos;ed\&apos;ff\&apos;f8\&apos;ed\&apos;e8\&apos;e9 \&apos;e4\&apos;e5\&apos;ed\&apos;fc 1,3 \&apos;ec\&apos;e8\&apos;eb\&apos;eb\&apos;e8\&apos;e0\&apos;f0\&apos;e4\&apos;e0 \&apos;ed\&apos;e0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string statistic {
            get {
                return ResourceManager.GetString("statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;c2\&apos;eb\&apos;e8\&apos;ff\&apos;e5\&apos;f2 \&apos;eb\&apos;e8 \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5 \&apos;ed\&apos;e0 \&apos;e2\&apos;e5\&apos;f1\f1\lang1033 ?\f0\lang1049\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\b0\tab\&apos;cc\&apos;ed\&apos;ee\&apos;e3\&apos;e8\&apos;e5 \&apos;ea\&apos;f3\&apos;f0\&apos;ff\&apos;f9\&apos;e8\&apos;e5 \&apos;eb\&apos;fe\&apos;e4\&apos;e8 \&apos;ef\&apos;f0\&apos;e5\&apos;ea\&apos;f0\&apos;e0\&apos;f1\&apos;ed\&apos;ee \&apos;e7\&apos;ed\&apos;e0\&apos;fe\&apos;f2, \&apos;ed\&apos;e0\&apos;f1\&apos;ea\&apos;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}{\f2\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;ca\&apos;f2\&apos;ee \&apos;e8 \&apos;ea\&apos;e0\&apos;ea \&apos;e7\&apos;e0\&apos;f1\&apos;f2\&apos;e0\&apos;e2\&apos;eb\&apos;ff\&apos;e5\&apos;f2 \&apos;ed\&apos;e0\&apos;f1 \&apos;ea\&apos;f3\&apos;f0\&apos;e8\&apos;f2\&apos;fc?\b0\f1\lang1033\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\tab\f0\lang1049\&apos;c2 \&apos;d5\&apos;d5 \&apos;e2\&apos;e5\&apos;ea\&apos;e5 \&apos;ee\&apos;f2 \&apos;e1\&apos;ee\&apos;eb\&apos;e5\&apos;e7\&apos;ed\&apos;e5\&apos;e9, \&apos;f1\&apos;e2\&apos;ff\&apos;e7\&apos;e0\&apos;ed\&apos;ed\&apos;fb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string whonhow {
            get {
                return ResourceManager.GetString("whonhow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}{\f2\fnil\fcharset0 Calibri;}{\f3\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;cf\&apos;ee\&apos;f7\&apos;e5\&apos;ec\&apos;f3 \&apos;c2\&apos;fb \&apos;e4\&apos;f3\&apos;ec\&apos;e0\&apos;e5\&apos;f2\&apos;e5, \&apos;f7\&apos;f2\&apos;ee \&apos;c2\&apos;e0\&apos;ec \&apos;ef\&apos;ee\&apos;e2\&apos;e5\&apos;e7\&apos;e5\&apos;f2?\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\b0\tab\&apos;c2\&apos;fb \&apos;e3\&apos;eb\&apos;f3\&apos;e1\&apos;ee\&apos;ea\&apos;ee \&apos;ee\&apos;f8\&apos;e8\&apos;e1\&apos;e0\&apos;e5\&apos;f2\&apos;e5\&apos;f1\&apos;fc, \&apos;e5\&apos;f1\&apos;eb\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string whyuthink {
            get {
                return ResourceManager.GetString("whyuthink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}{\f2\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;ca\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5 \&apos;e8 \&apos;e0\&apos;eb\&apos;ea\&apos;ee\&apos;e3\&apos;ee\&apos;eb\&apos;fc\b0\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\tab\&apos;ca\&apos;e0\&apos;e6\&apos;e4\&apos;fb\&apos;e9 \&apos;f5\&apos;ee\&apos;f2\&apos;fc \&apos;f0\&apos;e0\&apos;e7 \&apos;e2 \&apos;e6\&apos;e8\&apos;e7\&apos;ed\&apos;e8 \&apos;e8\&apos;ec\&apos;e5\&apos;eb \&apos;e2\&apos;ee\&apos;e7\&apos;ec\&apos;ee\&apos;e6\&apos;ed\&apos;ee\&apos;f1\&apos;f2\&apos;fc \&apos;ed\&apos;e0\&apos;e1\&apos;eb\&apos;fe\&apos;e4\&apos;e0\&apos;f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string withalc {
            get {
                return ResourceManager.GetString("withalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1251\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil Calibri;}}
        ///{\*\generator Riched20 10.0.10586}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\qc\b\f0\fs22\lang1049\&apos;ca\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5 \&apos;e8 \&apos;f1\&apos;ef\&apos;ee\&apos;f0\&apos;f2\b0\par
        ///
        ///\pard\sa200\sl276\slmult1\qj\tab\&apos;ce \&apos;f2\&apos;ee\&apos;ec, \&apos;f7\&apos;f2\&apos;ee \&apos;ea\&apos;f3\&apos;f0\&apos;e5\&apos;ed\&apos;e8\&apos;e5 \f1\endash  \f0\&apos;fd\&apos;f2\&apos;ee \&apos;ee\&apos;e4\&apos;ed\&apos;e0 \&apos;e8\&apos;e7 \&apos;f1\&apos;e0\&apos;ec\&apos;fb\&apos;f5 \&apos;e2\&apos;f0\&apos;e5\&apos;e4\&apos;ed\&apos;fb\&apos;f5 \&apos;ef\&apos;f0\&apos;e8\&apos;e2\&apos;fb\&apos;f7\&apos;e5\&apos;ea, \&apos;ea\&apos;e0\&apos;e6\&apos;e4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string withsport {
            get {
                return ResourceManager.GetString("withsport", resourceCulture);
            }
        }
    }
}
